name: Build Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Cargo Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - macOS-latest
#          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release
      - run: mv tavern tavern-server
      - uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: tavern-server
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
